# Generated by Django 5.1.4 on 2025-01-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, unique=True)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_address', models.TextField()),
                ('vehicle_make', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('is_stolen', models.BooleanField(default=False)),
                ('outstanding_warrants', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
